export default {
  SET_FORM_PROPERTY: 'TASK/SET_FORM_PROPERTY',
  ADD_INPUT: 'FORM/ADD_INPUT',
  SET_INPUT: 'FORM/SET_INPUT',
  UPDATE_TITLE_CONTAINER: 'TITLE_CONTAINER/UPDATE_TITLE_CONTAINER',
  DELETE_INPUT_FROM_AND_DATA: 'FORM/DELETE_INPUT_FROM_AND_DATA',
};
